name: Yelan - Create New Project

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nama Repositori Baru'
        required: True
        default: 'Vanguard-Project'

jobs:
  build_repo:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Execute Yelan
        env:
          YELAN_PAT: ${{ secrets.YELAN_PAT }}
          TARGET_REPO_NAME: ${{ github.event.inputs.repo_name }}
        run: python yelan_core.py
