name: Yelan Handshake

on:
  workflow_dispatch:

jobs:
  test_connection:
    runs-on: ubuntu-latest
    env:
      # Inilah baris 'pemaksa' agar warning hilang
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run Handshake
        env:
          YELAN_PAT: ${{ secrets.YELAN_PAT }}
        run: python yelan_core.py
